//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFTP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }





        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.16.57.21")]
        public string OBJECTSTORAGE_HOST
        {
            get
            {
                return ((string)(this["OBJECTSTORAGE_HOST"]));
            }
            set
            {
                this["OBJECTSTORAGE_HOST"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32728")]
        public string OBJECTSTORAGE_PORT
        {
            get
            {
                return ((string)(this["OBJECTSTORAGE_PORT"]));
            }
            set
            {
                this["OBJECTSTORAGE_PORT"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file-lake-consumer")]
        public string BUCKET_NAME
        {
            get
            {
                return ((string)(this["BUCKET_NAME"]));
            }
            set
            {
                this["BUCKET_NAME"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OBJECTSTORAGE_REGION
        {
            get
            {
                return ((string)(this["OBJECTSTORAGE_REGION"]));
            }
            set
            {
                this["OBJECTSTORAGE_REGION"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nileadmin")]
        public string OBJECTSTORAGE_USER
        {
            get
            {
                return ((string)(this["OBJECTSTORAGE_USER"]));
            }
            set
            {
                this["OBJECTSTORAGE_USER"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nile20211201!")]
        public string OBJECTSTORAGE_PW
        {
            get
            {
                return ((string)(this["OBJECTSTORAGE_PW"]));
            }
            set
            {
                this["OBJECTSTORAGE_PW"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.16.57.26:32272")]
        public string BOOTSTRAP_SERVERS
        {
            get
            {
                return ((string)(this["BOOTSTRAP_SERVERS"]));
            }
            set
            {
                this["BOOTSTRAP_SERVERS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file-to-lake")]
        public string TOPIC_NAME
        {
            get
            {
                return ((string)(this["TOPIC_NAME"]));
            }
            set
            {
                this["TOPIC_NAME"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string SYNC_DIR
        {
            get
            {
                return ((string)(this["SYNC_DIR"]));
            }
            set
            {
                this["SYNC_DIR"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("png; jpg; mp4; avi")]
        public string UPLOAD_ONLY_EXTENSIONS
        {
            get
            {
                return ((string)(this["UPLOAD_ONLY_EXTENSIONS"]));
            }
            set
            {
                this["UPLOAD_ONLY_EXTENSIONS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("csv; txt")]
        public string CSV_EXTENSIONS
        {
            get
            {
                return ((string)(this["CSV_EXTENSIONS"]));
            }
            set
            {
                this["CSV_EXTENSIONS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("json")]
        public string JSON_EXTENSIONS
        {
            get
            {
                return ((string)(this["JSON_EXTENSIONS"]));
            }
            set
            {
                this["JSON_EXTENSIONS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iceberg")]
        public string TARGET_TYPE
        {
            get
            {
                return ((string)(this["TARGET_TYPE"]));
            }
            set
            {
                this["TARGET_TYPE"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iceberg_catalog")]
        public string TARGET_CATALOG
        {
            get
            {
                return ((string)(this["TARGET_CATALOG"]));
            }
            set
            {
                this["TARGET_CATALOG"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file_to_lake")]
        public string TARGET_DATABASE
        {
            get
            {
                return ((string)(this["TARGET_DATABASE"]));
            }
            set
            {
                this["TARGET_DATABASE"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("test_object_transfer_etl")]
        public string TARGET_TABLE
        {
            get
            {
                return ((string)(this["TARGET_TABLE"]));
            }
            set
            {
                this["TARGET_TABLE"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string CSV_DELIMITER
        {
            get
            {
                return ((string)(this["CSV_DELIMITER"]));
            }
            set
            {
                this["CSV_DELIMITER"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CSV_HEADER
        {
            get
            {
                return ((bool)(this["CSV_HEADER"]));
            }
            set
            {
                this["CSV_HEADER"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("testingHeader1, testingHeader2, testingHeader3")]
        public string CSV_CUSTOM_HEADER
        {
            get
            {
                return ((string)(this["CSV_CUSTOM_HEADER"]));
            }
            set
            {
                this["CSV_CUSTOM_HEADER"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EUC-KR")]
        public string CSV_ENCODING_TYPE
        {
            get
            {
                return ((string)(this["CSV_ENCODING_TYPE"]));
            }
            set
            {
                this["CSV_ENCODING_TYPE"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JSON_SELECTED_KEY
        {
            get
            {
                return ((string)(this["JSON_SELECTED_KEY"]));
            }
            set
            {
                this["JSON_SELECTED_KEY"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string SYNC_INVL_HR
        {
            get
            {
                return ((string)(this["SYNC_INVL_HR"]));
            }
            set
            {
                this["SYNC_INVL_HR"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string SYNC_INVL_MIN
        {
            get
            {
                return ((string)(this["SYNC_INVL_MIN"]));
            }
            set
            {
                this["SYNC_INVL_MIN"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LOG_SAVE
        {
            get
            {
                return ((bool)(this["LOG_SAVE"]));
            }
            set
            {
                this["LOG_SAVE"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CSV_JSON_ETL")]
        public string SPARK_APP_NAME
        {
            get
            {
                return ((string)(this["SPARK_APP_NAME"]));
            }
            set
            {
                this["SPARK_APP_NAME"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("local[*]")]
        public string SPARK_SET_MASTER
        {
            get
            {
                return ((string)(this["SPARK_SET_MASTER"]));
            }
            set
            {
                this["SPARK_SET_MASTER"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TASK_ETL_DATA")]
        public string SPARK_TASK_ID
        {
            get
            {
                return ((string)(this["SPARK_TASK_ID"]));
            }
            set
            {
                this["SPARK_TASK_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"key\": \"spark.sql.extensions\",\"value\": \"org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions\"},{\"key\": \"spark.sql.catalog.spark_catalog\",\"value\": \"org.apache.iceberg.spark.SparkSessionCatalog\"},{\"key\": \"spark.sql.catalogImplementation\",\"value\": \"hive\"},{\"key\": \"spark.sql.catalog.spark_catalog.type\",\"value\": \"hive\"},{\"key\": \"spark.sql.catalog.iceberg_catalog\",\"value\": \"org.apache.iceberg.spark.SparkCatalog\"},{\"key\": \"spark.sql.catalog.iceberg_catalog.type\",\"value\": \"hive\"},{\"key\": \"spark.sql.catalog.iceberg_catalog.warehouse\",\"value\": \"s3a://iceberg/spark/\"},{\"key\": \"spark.sql.catalog.iceberg_catalog.s3.endpoint\",\"value\": \"http://172.16.57.21:32728\"},{\"key\": \"spark.sql.catalogImplementation\",\"value\": \"in-memory\"},{\"key\": \"spark.executor.heartbeatInterval\",\"value\": \"300000\"},{\"key\": \"spark.network.timeout\",\"value\": \"400000\"},{\"key\": \"hive.metastore.uris\",\"value\": \"thrift://172.16.57.21:31160\"},{\"key\": \"spark.hadoop.fs.s3a.access.key\",\"value\": \"nileadmin\"},{\"key\": \"spark.hadoop.fs.s3a.secret.key\",\"value\": \"nile20211201!\"},{\"key\": \"spark.hadoop.fs.s3a.impl\",\"value\": \"org.apache.hadoop.fs.s3a.S3AFileSystem\"},{\"key\": \"spark.hadoop.fs.s3a.endpoint\",\"value\": \"http://172.16.57.21:32728\"},{\"key\": \"spark.hadoop.fs.s3a.connection.ssl.enabled\",\"value\": \"false\"},{\"key\": \"spark.hadoop.fs.s3a.path.style.access\",\"value\": \"true\"},{\"key\": \"spark.hadoop.fs.s3a.attempts.maximum\",\"value\": \"1\"},{\"key\": \"spark.hadoop.fs.s3a.connection.establish.timeout\",\"value\": \"5000\"},{\"key\": \"spark.hadoop.fs.s3a.connection.timeout\",\"value\": \"10000\"},{\"key\": \"spark.sql.iceberg.format-version\",\"value\": \"2\"}")]
        public string SPARK_CONFIGS
        {
            get
            {
                return ((string)(this["SPARK_CONFIGS"]));
            }
            set
            {
                this["SPARK_CONFIGS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OBJECT-TRANSFER-ETL")]
        public string APP_NAME
        {
            get
            {
                return ((string)(this["APP_NAME"]));
            }
            set
            {
                this["APP_NAME"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("local[*]")]
        public string SET_MASTER
        {
            get
            {
                return ((string)(this["SET_MASTER"]));
            }
            set
            {
                this["SET_MASTER"] = value;
            }
        }




    }
}
